# This file lists the dependencies needed to build and test all of svgdigitizer.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: svgdigitizer-build
channels:
  - conda-forge
dependencies:
  - astropy>=5,<6
  - black
  - click>=8,<9
  - frictionless>=5.8.3,<6
  - isort
  - jupytext
  - matplotlib-base>=3.5,<4
  - mergedeep>=1.3.4,<2
  - myst-parser
  - myst-nb
  - pandas>=1.3,<2
  - pdf2image>=1.16,<2
  - pillow>=10.0.1,<11
  - pip
  - poppler
  - pybtex>=0.24,<0.25
  - pylint
  - pytest
  - python
  - pyyaml>=6,<7
  - scipy>=1.7,<2
  - sphinx
  - svg.path>=4.1,<5
  - svgpathtools>=1.4,<2
  - svgwrite>=1.4,<2
  - pip:
    - linkchecker
    - sphinx_rtd_theme
    - sphinx-design
